// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqDc_FD_WYUot8adXe7ZpbN32uWCVU0YM',
    appId: '1:3447803267:android:7c1a494cd084ada06afab6',
    messagingSenderId: '3447803267',
    projectId: 'stacked-000',
    storageBucket: 'stacked-000.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3pHgvkym8PXCe58JcSbudZsSZH8pmiB0',
    appId: '1:3447803267:ios:cd34dd070f57b8bb6afab6',
    messagingSenderId: '3447803267',
    projectId: 'stacked-000',
    storageBucket: 'stacked-000.appspot.com',
    androidClientId: '3447803267-vi8b11gedrdn8vbrr8t1gf810asljupt.apps.googleusercontent.com',
    iosClientId: '3447803267-j0c15otg9n1qup996n7d6act7gg8k72j.apps.googleusercontent.com',
    iosBundleId: 'com.example.scoutsApp',
  );
}
